UI/Areas/Admin/Controllers/AddressController.cs
using BLL;
using DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Areas.Admin.Controllers
{
  public class AddressController : BaseController
  {
    public readonly AddressBLL bll = new AddressBLL();


    public ActionResult AddressList()
    {
      List<AddressDTO> model = bll.GetAddress();
      return View(model);
    }
    public ActionResult AddAddress()
    {
      AddressDTO dto = new AddressDTO();
      return View(dto);
    }

    [HttpPost]
    public ActionResult AddAddress(AddressDTO model)
    {
      if (ModelState.IsValid)
      {
        if (bll.AddAddress(model))
        {
          ViewBag.ProcessState = General.Messages.AddSuccess;
          ModelState.Clear();
          model = new AddressDTO();
        }
        else
        {
          ViewBag.ProcessState = General.Messages.GeneralError;
        }
      }
      else
      {
        ViewBag.ProcessState = General.Messages.EmptyArea;
      }

      return View(model);
    }

    public ActionResult UpdateAddress(int ID)
    {
      AddressDTO model = new AddressDTO();
      model = bll.GetAddressID(ID);
      return View(model);
    }

    [HttpPost]
    public ActionResult UpdateAddress(AddressDTO model)
    {
      if (ModelState.IsValid)
      {
        if (bll.UpdateMeta(model))
        {
          ViewBag.ProcessState = General.Messages.UpdateSuccess;
        }
        else
        {
          ViewBag.ProcessState = General.Messages.GeneralError;
        }
      }

      else
      {
        ViewBag.ProcessState = General.Messages.EmptyArea;
      }

      return View(model);
    }

    public JsonResult DeleteAddress(int ID)
    {
      bll.DeleteAddress(ID);
        return Json("");
    }


  }
}

UI/Areas/Admin/Views/Address/AddAddress.cshtml
@{
  ViewBag.Title = "AddAddress";
  Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<section class="content-header">
  <h1>Add Address Operation</h1>
  <ol class="breadcrumb float-sm-left">
    <li class="breadcrumb-item"><a>Admin</a></li>
    <li class="breadcrumb-item"><a>Address</a></li>
    <li class="breadcrumb-item active"><a>Add Address</a></li>
  </ol>
</section>
<br />
<div class="card-footer">
  <button type="submit" class="btn btn-primary" onclick="window.location.href='/Admin/Address/AddressList'">Address List</button>
</div>

<section class="content">
  <div class="row">
    <div class="col-md-9">
      @Html.Partial("~/Areas/Admin/Views/Shared/MessageForm.cshtml")
      <div class="box box-primary">
        @using (Html.BeginForm("AddAddress", "Address", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        {
          @Html.Partial("Partial/AddressForm")
        }
      </div>
    </div>
  </div>
</section>

UI/Areas/Admin/Views/Address/AddressList.cshtml
@{
    ViewBag.Title = "AddressList";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

@model List<DTO.AddressDTO>

<!-- Page Header -->
<section class="content-header mb-3">
    <h2 class="fw-bold text-dark">Address List</h2>
    <ol class="breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a href="#">Admin</a></li>
        <li class="breadcrumb-item"><a href="#">Address</a></li>
        <li class="breadcrumb-item active">Address List</li>
    </ol>
</section>

<!-- Add Address Button -->
<div class="card-footer border-0 bg-transparent mb-3">
    <button type="button" class="btn btn-dark px-4" onclick="window.location.href='/Admin/Address/AddAddress'">
        <i class="ion-ios-location-outline me-2"></i> Add Address
    </button>
</div>

<!-- Address Table -->
<div class="card shadow-sm border-0">
    <div class="card-header bg-white">
        <h5 class="card-title mb-0 text-dark">
            <i class="ion-ios-location me-2 mr-2"></i>Address Management
        </h5>
    </div>

    <div class="card-body">
        <table id="example1" class="table table-hover align-middle">
            <thead class="table-light">
                <tr>
                    <th>Address</th>
                    <th>Phone</th>
                    <th class="text-center">Update</th>
                    <th class="text-center">Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="a_@item.ID">
                        <td class="fw-semibold">@item.AddressContent</td>
                        <td>@item.Phone1</td>

                        <!-- UPDATE -->
                        <td class="text-center">
                            <a href="/Admin/Address/UpdateAddress/@item.ID"
                               class="text-decoration-none text-primary d-inline-flex align-items-center justify-content-center gap-2">
                                <i class="ion-edit"></i>
                                <span class="ml-2">Edit</span>
                            </a>
                        </td>

                        <!-- DELETE -->
                        <td class="text-center">
                            <a href="#"
                               class="text-decoration-none text-danger d-inline-flex align-items-center justify-content-center gap-2"
                               onclick="AskQuestion('/Admin/Address/DeleteAddress/', @item.ID)">
                                <i class="ion-trash-b"></i>
                                <span class="ml-2">Delete</span>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    @Html.Partial("~/Areas/Admin/Views/Shared/ModalMessage.cshtml")
</div>

<script src="~/Areas/Admin/Content/JS/DeleteRecord.js"></script>

UI/Areas/Admin/Views/Address/UpdateAddress.cshtml
@{
  ViewBag.Title = "UpdateAddress";
  Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}


<section class="content-header">
  <h1>Update Address Operation</h1>
  <ol class="breadcrumb float-sm-left">
    <li class="breadcrumb-item"><a>Admin</a></li>
    <li class="breadcrumb-item"><a>Address</a></li>
    <li class="breadcrumb-item active"><a>Update Address</a></li>
  </ol>
</section>
<br />
<div class="card-footer">
  <button type="submit" class="btn btn-primary" onclick="window.location.href='/Admin/Address/AddressList'">Address List</button>
</div>

<section class="content">
  <div class="row">
    <div class="col-md-9">
      @Html.Partial("~/Areas/Admin/Views/Shared/MessageForm.cshtml")
      <div class="box box-primary">
        @using (Html.BeginForm("UpdateAddress", "Address", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        {
          @Html.Partial("Partial/AddressForm")
        }
      </div>
    </div>
  </div>
</section>